### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by eranimo** [dwb/jsonrpc2-zeromq-python#4]
The main dependency here is [pyzmq](https://github.com/zeromq/pyzmq), which supports Python 3. What is preventing this project from supporting Python 3?

**Comment by dwb** [comment]
Merely my time and effort :) A branch is underway!

**Comment by dwb** [comment]
@eranimo: I've got tests passing on Python 3; if you have a minute I'd appreciate you trying it out. Branch here: https://github.com/dwb/jsonrpc2-zeromq-python/tree/py3

**Comment by dwb** [comment]
I've tested this a bit and am pretty confident of it being okay. I've bumped the major version though, in case there's some subtle backwards incompatibility.
